# Notebook 02: Data Cleaning & Feature Selection

## Objectives

In this notebook we will:

- Load the processed dataset
- Check data quality
- Handle missing values
- Remove unnecessary columns
- Select input features
- Define the target variable
- Split the dataset into training and testing sets
- Save the processed datasets for model training

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/processed/clean_dataset.csv")

df.head()

,Sample,Droplet diameter [m],Impact velocity [m/s],Density [kg/m3],Surface Tension [N/m],Dynamic Viscosity [Pa s],Distance between adjacent laser beam passes [µm],Average depth of micro-channels [µm],Reynolds number,Weber number,Contact time [s],Rebound efficiency,Spreading coefficient,Lamella velocity [m/s]
0,D50,0.002474,0.536894,997.2375,0.07246,0.000944,50,25,1403.137456,9.813564,0.0116,0.379821,1.560187,0.630631
1,D50,0.002448,0.520219,997.2375,0.07246,0.000944,50,25,1345.333100,9.117050,0.0112,0.404025,1.561484,0.563939
2,D50,0.002458,0.525367,997.2375,0.07246,0.000944,50,25,1364.054232,9.335398,0.0114,0.390917,1.560394,0.626598
3,D50,0.002445,0.515020,997.2375,0.07246,0.000944,50,25,1330.085602,8.923632,0.0114,0.410316,1.558473,0.532609
4,D50,0.002456,0.523727,997.2375,0.07246,0.000944,50,25,1358.736271,9.269965,0.0114,0.397799,1.561609,0.595269

In [3]:
print("="*50)
print("Dataset Shape")
print(df.shape)

print("\n")

print("="*50)
print("Column Names")
print(df.columns.tolist())

==================================================
Dataset Shape
(1498, 14)


==================================================
Column Names
['Sample', 'Droplet diameter [m]', 'Impact velocity [m/s]', 'Density [kg/m3]', 'Surface Tension [N/m]', 'Dynamic Viscosity [Pa s]', 'Distance between adjacent laser beam passes [µm]', 'Average depth of micro-channels [µm]', 'Reynolds number', 'Weber number', 'Contact time [s]', 'Rebound efficiency', 'Spreading coefficient', 'Lamella velocity [m/s]']

In [4]:
print("Missing Values")

df.isnull().sum()

Missing Values

Sample                                              0
Droplet diameter [m]                                0
Impact velocity [m/s]                               0
Density [kg/m3]                                     0
Surface Tension [N/m]                               0
Dynamic Viscosity [Pa s]                            0
Distance between adjacent laser beam passes [µm]    0
Average depth of micro-channels [µm]                0
Reynolds number                                     0
Weber number                                        0
Contact time [s]                                    0
Rebound efficiency                                  0
Spreading coefficient                               0
Lamella velocity [m/s]                              0
dtype: int64

In [5]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [6]:
# Display all column names clearly

for i, col in enumerate(df.columns):
    print(f"{i:2d} : {col}")

 0 : Sample
 1 : Droplet diameter [m]
 2 : Impact velocity [m/s]
 3 : Density [kg/m3]
 4 : Surface Tension [N/m]
 5 : Dynamic Viscosity [Pa s]
 6 : Distance between adjacent laser beam passes [µm]
 7 : Average depth of micro-channels [µm]
 8 : Reynolds number
 9 : Weber number
10 : Contact time [s]
11 : Rebound efficiency
12 : Spreading coefficient
13 : Lamella velocity [m/s]

In [ ]:
# Features (X)
#no contact time, Reebound Efficiency and Lamella velocity to avoid Data Leakage
feature_columns = [
    "Droplet diameter [m]",
    "Impact velocity [m/s]",
    "Density [kg/m3]",
    "Surface Tension [N/m]",
    "Dynamic Viscosity [Pa s]",
    "Distance between adjacent laser beam passes [µm]",
    "Average depth of micro-channels [µm]",
    "Reynolds number",
    "Weber number"
]

# Target (y)

target_column = "Spreading coefficient"

X = df[feature_columns]
y = df[target_column]

print("Features Shape :", X.shape)
print("Target Shape   :", y.shape)

Features Shape : (1498, 9)
Target Shape   : (1498,)

In [8]:
X.head()

,Droplet diameter [m],Impact velocity [m/s],Density [kg/m3],Surface Tension [N/m],Dynamic Viscosity [Pa s],Distance between adjacent laser beam passes [µm],Average depth of micro-channels [µm],Reynolds number,Weber number
0,0.002474,0.536894,997.2375,0.07246,0.000944,50,25,1403.137456,9.813564
1,0.002448,0.520219,997.2375,0.07246,0.000944,50,25,1345.333100,9.117050
2,0.002458,0.525367,997.2375,0.07246,0.000944,50,25,1364.054232,9.335398
3,0.002445,0.515020,997.2375,0.07246,0.000944,50,25,1330.085602,8.923632
4,0.002456,0.523727,997.2375,0.07246,0.000944,50,25,1358.736271,9.269965

In [9]:
y.head()

0    1.560187
1    1.561484
2    1.560394
3    1.558473
4    1.561609
Name: Spreading coefficient, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Samples :", len(X_train))
print("Testing Samples  :", len(X_test))

Training Samples : 1198
Testing Samples  : 300

In [11]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)

print("Datasets Saved Successfully!")

Datasets Saved Successfully!

In [12]:
print("="*50)
print("Notebook 02 Completed")
print("="*50)

print(f"Total Samples      : {len(df)}")
print(f"Training Samples   : {len(X_train)}")
print(f"Testing Samples    : {len(X_test)}")
print(f"Number of Features : {X.shape[1]}")
print(f"Target Variable    : {target_column}")

==================================================
Notebook 02 Completed
==================================================
Total Samples      : 1498
Training Samples   : 1198
Testing Samples    : 300
Number of Features : 9
Target Variable    : Spreading coefficient